# SPDX-License-Identifier: GPL-2.0

# Source files
# os_tcl.c 
${BUILD_LIB}_FILES +=  \
    os.c \
    os_cable.c \
    os_mem.c \
    os_pthread.c \
    os_string.c \
    os_timer.c \
    os_trap.c

# Source paths
SRC_PATH +=  $(GLOBALPATH)/os
