# SPDX-License-Identifier: GPL-2.0

# Source files
${BUILD_LIB}_FILES +=  \
    os.c \
    os_mem.c \
    os_pthread.c \
    os_shm.c \
    os_string.c \
    os_trap.c

# Source paths
SRC_PATH +=  $(GLOBALPATH)/os
