# SPDX-License-Identifier: GPL-2.0

# Source files
${BUILD_LIB}_FILES +=  \
    os.c \
    os_buffer.c \
    os_cable.c \
    os_clock.c \
    os_inet.c \
    os_mem.c \
    os_pthread.c \
    os_string.c \
    os_tcl.c \
    os_trap.c

# Source paths
SRC_PATH +=  $(GLOBALPATH)/os
