# export CROSS_COMPILE=
# export ARCH=x86_64

obj-m += hello_world.o

# run kernel build system to make module
all:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules

# run kernel build system to cleanup in current directory
clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean
